#!/bin/bash

#PBS -q nbns
#PBS -l arch=x86_64,walltime=4:00:00,nodes=1:ppn=1
#PBS -V
#PBS -e /home/rcf-104/patrices/opt/cvmsi/scripts/text2grid_i0.err
#PBS -o /home/rcf-104/patrices/opt/cvmsi/scripts/text2grid_i0.out

SRC_DIR=/home/rcf-104/patrices/opt/cvmsi/scripts

cd ${SRC_DIR}

./Text2Grid.py -i 0 /home/rcf-104/patrices/opt/cvmsi.old/model CVM4MDL_ 992 1536 100 ./cvmsi_i0.bin

echo "Jobs done"
date
exit 0
