package:
  name: ucvm
  version: 17.3.0

source:
  git_url: https://github.com/SCECcode/UCVM.git

requirements:
  build:
    - python ==3.5
    - setuptools
    - basemap ==1.0.7
    - h5py
    - xmltodict
    - humanize
    - pyproj
    - psutil
    - matplotlib
    - mpi4py

  run:
    - python ==3.5
    - setuptools
    - basemap ==1.0.7
    - h5py
    - xmltodict
    - humanize
    - pyproj
    - psutil
    - matplotlib
    - mpi4py

test:
  imports:
    -

about:
  home: https://github.com/SCECcode/UCVM
  license: Apache 2.0
  license_file: LICENSE