package:
  name: ucvm
  version: 17.3.0

source:
  git_url: https://github.com/SCECcode/UCVM.git

requirements:
  build:
    - python ==3.5
    - setuptools
    - basemap ==1.0.7
    - pyqt ==5.6 [osx]
    - icu ==56 [linux]
    - h5py
    - xmltodict
    - humanize
    - pyproj
    - psutil
    - matplotlib
    - mpi4py
    - pillow

  run:
    - python ==3.5
    - setuptools
    - basemap ==1.0.7
    - pyqt ==5.6 [osx]
    - icu ==56 [linux]
    - h5py
    - xmltodict
    - humanize
    - pyproj
    - psutil
    - matplotlib
    - mpi4py
    - pillow

about:
  home: https://github.com/SCECcode/UCVM
  license: Apache 2.0
  license_file: LICENSE
